<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BuildDate>$([System.DateTime]::Now.ToString('yyyyMMdd'))</BuildDate>
    <BuildTime>$([System.DateTime]::Now.ToString('HHmmss'))</BuildTime>
    <Version>1.0.1+$(BuildDate)$(BuildTime)</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SaxsSpot.Core.Contracts\SaxsSpot.Core.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Contracts\" />
  </ItemGroup>
</Project>